// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKS0OgiQklYdnKRS8sk0jhferdnjK1_KA',
    appId: '1:774026032975:android:21459e1c21627aec9ef73a',
    messagingSenderId: '774026032975',
    projectId: 'shoppinglistapp-12cb6',
    databaseURL: 'https://shoppinglistapp-12cb6-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglistapp-12cb6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFnINZOAbz0w1Q_9bH0eXvJzYnxX-_mg',
    appId: '1:774026032975:web:596a079c029732569ef73a',
    messagingSenderId: '774026032975',
    projectId: 'shoppinglistapp-12cb6',
    authDomain: 'shoppinglistapp-12cb6.firebaseapp.com',
    databaseURL: 'https://shoppinglistapp-12cb6-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglistapp-12cb6.appspot.com',
    measurementId: 'G-ZLJR5F3SWX',
  );
}
